### ISSUE TITLE
Answer format for seq2seq models

### ISSUE THREAD

**Issue by carlos-gemmell** [amazon-research/mintaka#1]
Hi, Thanks for the great resource!

I was wondering what is the correct way to evaluate seq2seq models (like CBQA T5 in your paper) on your data.
For instance, question id `88bdb808` in `mintaka_dev.json` is a count based question but has answer type "entity". Would the target answer be "6"? one of the entities? all of the entities exactly?
This applies in other situations like the comparative and SUPERLATIVE where it is not clear when to use the `mention` or `answerNum` as the ground truth.

Would it be possible to provide a script denoting the target labels for hits@1 please?

Best,
Carlos

**Comment by priyanka-sen** [comment]
Hi! Sorry about the delay! We made the changes on Oct 25 but forgot to close this issue. 
1) Superlative and Count questions are reformatted with an additional supportingNum or supportingEnt field to distinguish between the answer and supporting information.
2) An evaluation script is available! See [Evaluation](https://github.com/amazon-science/mintaka#evaluation). To evaluate with a T5-like model, you can run something like

```
python evaluate/evaluate.py \
  --mode text \
  --path_to_predictions evaluate/examples/example_text_predictions.json \
  --lang en
```
